# Generated by Django 6.0.5 on 2026-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_statut_en_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voitures/'),
        ),
    ]
