# Generated by Django 6.0.6 on 2026-06-17 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_voiture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='voiture',
            name='annee',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990, message="L'année doit être >= 1990."), django.core.validators.MaxValueValidator(2027, message="L'année ne peut pas dépasser 2027.")]),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='prix_jour',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Le prix par jour doit être positif.')]),
        ),
        migrations.AddField(
            model_name='voiture',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voitures', to='core.categorie'),
        ),
    ]
