# Generated by Django 6.0.6 on 2026-06-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categorie_alter_voiture_annee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Especes'), ('virement', 'Virement'), ('carte', 'Carte bancaire')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('paye', 'Paye'), ('en_attente', 'En attente'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.reservation')),
            ],
        ),
    ]
