# Generated by Django 6.0.6 on 2026-06-17 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('validation', 'Validation'), ('refus', 'Refus'), ('annulation', 'Annulation'), ('paiement', 'Paiement'), ('retour', 'Retour'), ('inscription', 'Inscription'), ('connexion', 'Connexion'), ('modification', 'Modification')], max_length=20)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='core.reservation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historiques',
                'ordering': ['-date_action'],
            },
        ),
    ]
