# Generated by Django 6.0.6 on 2026-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_retour_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
